## Cutlery config file

## Sample information file with tab-delimited five columns: id / name / group / fq1 / fq2
sampleInfo: sample.tsv

#########################
## Directories
## This directory setting helps running Cutlery with different setting from intermediate results in a different folder keeping previous results
## These can be left as is if you aren't sure what to do with them
## Directory containing fastq files
fastqDir:   0.Fastq
## Directory for trimmed fastq files
trimDir:    0.Fastq.Trim
## Directory for alignment results
alignDir:   1.1.Align
## Directory for deduplicated bam file. Ignored if doDeup==False
dedupDir:   1.3.Align.dedup
## Directory of Quality control results
qcDir:      2.1.QualityControl
## Directory processed results for each sample
sampleDir:  3.Sample
## Directory for Homer motif background
homerPreparseDir: /data/limlab/Resource/Homer.preparse

#########################
## Genome reference

## mouse genome mm10
# Genome fasta file (single). Matching index file must exists (*.fai from samtools faidx)
genomeFa:   /data/limlab/Resource/GenomeData/mm/mm10/Genome/genome.fa
# Chromosome size file. tab-delimited: chr / size
# It is OK to use chrNameLength.txt in STAR index
chrom_size: /data/limlab/Resource/GenomeData/mm/mm10/Genome/chrom.size
# Blacklist region bed file for peak, e.g. ENCODE blacklist. "NULL" if no black list to be used
peak_mask:  /data/limlab/Resource/GenomeData/mm/mm10/ENCODE-blacklist.bed
# Genome. used for genome specification in Homer motif search. The corresponding genome must be available in Homer installation
genome:     mm10
# STAR index folder
star_index: /data/limlab/Resource/STAR_Index/2.7.4/mm10_allChr_vM20

# ## human genome hg38
# genomeFa:   /data/limlab/Resource/GenomeData/hg/hg38/Genome/genome.fa
# chrom_size: /data/limlab/Resource/GenomeData/hg/hg38/Genome/chrom.size
# peak_mask:  /data/limlab/Resource/GenomeData/hg/hg38/ENCODE-blacklist.bed
# genome:     hg38
# star_index: /data/limlab/Resource/STAR_Index/2.7.4/hg38_allChr_v29

# ## zebrefish genome danRer11
# genomeFa:   /data/limlab/Resource/GenomeData/danRer11/Genome/genome.fa
# chrom_size: /data/limlab/Resource/GenomeData/danRer11/Genome/chrom.size
# peak_mask:  /data/limlab/Resource/GenomeData/danRer11/blacklist.danRer11.bed
# genome:     danRer11
# star_index: /data/limlab/Resource/STAR_Index/2.7.4/danRer11


#########################
## Other parameters

## STAR options; these settings are recommended and can be left as is
star_option: --alignSJDBoverhangMin 999 --alignIntronMax 1 --alignMatesGapMax 1000 --outFilterMultimapNmax 1 --outFilterMismatchNoverLmax 0.05 --outReadsUnmapped None --alignEndsProtrude 2 ConcordantPair

## adapter trimming; set as "NULL" if you do not want to perform trimming
## illumina universal adapter = "AGATCGGAAGAGC"
## Nextera adapter for ATAC-seq or Cut&Tag = "CTGTCTCTTATA"
adapter: AGATCGGAAGAGC

## additional options for cutadapt; follow cutadapt syntax. Leave as empty quotes if no additional options are being used.
## default parameters: minimum fragment length 20, minimum quality 20 for quality trimming
min_fragment_length: 20
min_quality: 20
## additional options for cutadapt; default is empty and can be left as is
cutadapt_options: ""

## deduplication (not recommended)
doDedup: False

## Regular expressions for target chromosomes
chrRegexTarget: ^chr[0-9XY]+$

## Promoter bed file to check promoter signal enrichment e.g. for ATAC-seq
## Fixed window around TSS e.g. TSS +/- 1kb
## if bed file is set, will measure % of fragment within promoter regions defined in bed_promoter file
## as a quality measure for ATAC-seq data.
## set as NULL if not measuring promoter count
bed_promoter: NULL

## peak calling
## set as False if you don't need a particular type of analysis
peak_calling:
  homer:
    default: True
    all_fragments: False
  macs:
    default: False
    all_fragments:  False

## html report generation option
# {replicate,pool.NULL}
# replicate: replicate analysis
# pool: pooled analysis
# NULL: no report generation
html_report: replicate
